### ISSUE TITLE
Documentation on widgets ?

### ISSUE THREAD

**Issue by skysingh** [ropg/M5ez#17]
I am really enjoying your M5ez. I have ported my app to it and really like the event management. The multibutton code is very clever. I have figured most things out but:
1. I need the clock widget to access my external RTC. Is there a way ? 
2. Need more examples on how to create and use widgets.

**Comment by ropg** [comment]
I should make an example program for that, I know. Haven't had time. But here's a [thread](http://forum.m5stack.com/topic/262/m5ez-a-complete-interface-builder-system-for-the-m5stack-as-an-arduino-library-extremely-easy-to-use/76) on the M5Stack forum that may or may not help. Good luck...
