### ISSUE TITLE
Detect if WiFi is connected

### ISSUE THREAD

**Issue by TotallyInformation** [ropg/M5ez#2]
Hi, love this library and I believe it will make the M5Stack really usable.

However, I need to connect the device to MQTT using [this library](https://github.com/256dpi/arduino-mqtt) which I believe to be ESP32 compatible.

To do so, I need 2 things.

1. I need to know if the WiFi is actually connected and I can't work out how to do that with your library. I've done the usual check such as `if (WiFi.status() == WL_CONNECTED) {...}` but that never seems to be true.

2. I need to access a WiFiClient object - I am hoping that including `WiFiClient.h` will do the trick once I can get 1 working.

Any advice please? I have the latest versions of M5ez and the M5Stack.

**Comment by ropg** [comment]
> Hi, love this library and I believe it will make the M5Stack really usable.

Thanks... :)


> However, I need to connect the device to MQTT using this library which I believe to be ESP32 compatible.
> 
> To do so, I need 2 things.
> 
> 	• I need to know if the WiFi is actually connected and I can't work out how to do that with your library. I've done the usual check such as if (WiFi.status() == WL_CONNECTED) {...} but that never seems to be true.

I wouldn't know why that wouldn't work... Either that or WiFi.isConnected()  ??


> 
> 	• I need to access a WiFiClient object - I am hoping that including WiFiClient.h will do the trick once I can get 1 working.

Anything you would normally do should still work.



I am presently hurrying to Norway to search for a missing friend. But do mail me how it's going. We'll make it work.


Rop

**Comment by TotallyInformation** [comment]
I've seen the reports on Twitter. All the best for the search, I hope it goes well. I will keep experimenting as I have time. Forget this for now, sort out your friend.

**Comment by TotallyInformation** [comment]
Right, new day, new thoughts. I've refactored everything and I've got it working. Thanks for you previous response. I will publish the code when I can so that there is a concrete example for others.

I'm afraid that I think I will have other questions but I will wait until you aren't distracted with your search. Wish you all the very best on that again.
