### ISSUE TITLE
arduino meets micropython

### ISSUE THREAD

**Issue by ahaeberle** [ropg/M5ez#22]
Hi Rop,
did you look into Micro Python?

I really would like to see some parallel approaches like M5ez in parallel to a Micro Python stack. Or to use Micro Python like an on demand scripting language.
This would give the developer the best of both worlds ...
What do you think?

**Comment by ropg** [comment]
I'd love to offer M5ez with python bindings. It is my understanding that that would work with mostly existing code, it's just not something I have done before. I'd be very happy to work with someone who is a little more versed in that to make it happen though...

**Comment by ahaeberle** [comment]
OK, I do use C/C++ and Python heavily at work and have looked into some integration issues.
For Micro Python I have seen some examples. And a good presentation from https://www.youtube.com/watch?v=QPNmQZrG8ZU by Nick More the interesting details for the binding is from minute 18:00.
It is a bit layered because we have to wrap up a ctype to a python type, a c function to a python function, and filnally the items and the python module itself ...
I will try to gather some resources and give it a try.
Maybe I will bring in a colleague (student) do help me with the work.
Sincerely
  Felix

**Comment by ropg** [comment]
Cool. I'm here to help and I want to learn some of that stuff myself. I have limited python experience, but never really in getting python to talk to anything else. It would be cool if we could make M5ez be available in both worlds...

**Comment by ahaeberle** [comment]
OK, I mastered the next step - adding M5ez to a M5Stack sourcebase via Espressif component.
But I do miss most of the headers:
- M5Stack.h
- ezTime.h
- WiFi.h
- Preferences.h
- WiFiClientSecure.h
- Update.h

I am shure you know exactly where to look for them...

**Comment by ahaeberle** [comment]
found M5Stack.h
> https://github.com/m5stack/M5Stack

and eztime.h
> https://github.com/ropg/ezTime

and Preferences.h, WiFi.h, WiFiClientSecure.h, Update.h
> https://github.com/espressif/arduino-esp32

we will see if I can use them in the project or have to port them.
