### ISSUE TITLE
M5ez.cpp:1613:10: error: 'class UpdateClass' has no member named 'onProgress'    Update.onProgress(_update_progress);

### ISSUE THREAD

**Issue by rhannink** [ropg/M5ez#28]
Hello,

During compilation of the z-sysInfo.ino example I get the error:

M5ez.cpp:1613:10: error: 'class UpdateClass' has no member named 'onProgress'    Update.onProgress(_update_progress);

I use the latest version of the M5ez library, 2.0.1.

Any idea??

Gr. Remco

**Comment by ropg** [comment]
Hmmm, no. Strange. I’ll have a look later tonight or tomorrow.

**Comment by rhannink** [comment]
@ropg,

This issue seems to be fixen in the latest release off the Library. The z-sysInfo.ino example now compiles fine.

Thanks...
