### ISSUE TITLE
How to use an image as header for screen?

### ISSUE THREAD

**Issue by DaleMitchell** [ropg/M5ez#30]
I'd like to put an image in the header and then have a scrolling text console in the middle, not sure how to do it.

**Comment by ropg** [comment]
Cannot be done at present, but I guess you could put the image there from code, using `m5.lcd.drawJpg`.

**Comment by TimonPeng** [comment]
@ropg So it can't display Chinese too.

**Comment by ropg** [comment]
I have no idea... How do you normally display Chinese? Using the m5 libraries?
