### ISSUE TITLE
I'm having problems using GFX fonts.

### ISSUE THREAD

**Issue by DarkBeardRUS** [ropg/M5ez#31]
Hi,
I'm having problems using GFX fonts.

Sketch:
#include <M5Stack.h>
#include "FreeSerifBold9pt7b.h"

void setup() {
  m5.begin();
  m5.lcd.fillScreen(TFT_WHITE);
  m5.lcd.setTextColor(TFT_BLACK);
  m5.lcd.setTextDatum(CC_DATUM);
  m5.lcd.setFreeFont(&FreeSerifBold9pt7b);
  m5.lcd.drawString("Testing 123...", 160, 120);
}
void loop() {
}

Errors:
FreeSerifBold9pt7b.h:1:41: error: redefinition of 'const uint8_t FreeSerifBold9pt7bBitmaps []'
 const uint8_t FreeSerifBold9pt7bBitmaps[] PROGMEM = {

and several other similar errors
What am I doing wrong?
An example was taken here https://rop.nl/truetype2gfx/

**Comment by ropg** [comment]
Sorry for late reply. That name is already in use in the M5Stack library because it provides that font already.
