### ISSUE TITLE
Way to end ezMenu routine and free resources used?

### ISSUE THREAD

**Issue by groej** [ropg/M5ez#33]
Dear Rop,

thanks for the really nice program. My question is: I set up my m5stack with a mainmenu, all things work fine. Now I added an event routine which measures the temperature via a sensor wired to my stack. If the temperature rises over a certain max. limit I open a messagebox with a warning and this can be accepted by pressing "OK". After that the screen stays black, however I would like to switch back to the mainmenu. If I call up the mainmenu function (after "OK" is pressed) this works only about 5 times until the stack crashes (memory overflow) cause I started the mainmenu routine several times in my case. So question is, how can I stop the running instance (and free resources) of the mainmenu or how can I switch back to it? As far as I can see, this scenario is not foreseen, as a messagebox call always seem to be called from the menu itself by mainly user interaction so the route back to the mainmenu is clear. It would be nice to work with messageboxes as a "standalone" callup function and have a route back to the mainmenu.

Thank you in advance

groej

**Comment by ropg** [comment]
I just released version 2.1.2 which has an `ez.redraw()` function. From the new README:

#### Redrawing after an event

`void ez.redraw()`

Sometimes code executed in an event will have changed the contents of the screen. The running menu knows nothing about this, and so when your event ends, it will not refresh the screen. To fix this, you can execute ez.redraw() whenever your event routine has done something on the screen. The menu code will then redraw the screen accordingly.

> At present, only ezMenu knows about this redraw, so if the use was doing something else (like editing a text field or looking at a msgBox, the screen will not redraw. This is on the todo list.
