### ISSUE TITLE
Repeatedly restarts when updating with OTA.

### ISSUE THREAD

**Issue by HigashidaTomoyuki** [ropg/M5ez#35]
If you update with `OTA_https` of `examples`, reboot will be repeated. I do not know the solution. Also, please let me know if there is a way to do OTA using Bluetooth.

**Comment by laplanteliberee** [comment]
Same issue here?
Any solution? how to stop it or reset it? Cannot connect with arduino IDE

**Comment by ropg** [comment]
Strange. I'll get my M5Stack out and experiment at some point, but this used to work for me. Does the serial output show anything? It should show the unit booting at least, and then possibly a stack trace...

**Comment by laplanteliberee** [comment]
It constantly reboot, cannot access it anymore... not enough time to go to configure wifi
Serial monitor failed to connect to /dev/TTYUSB0

**Comment by laplanteliberee** [comment]
I managed to load another program (and stop it rebooting)
simply holding down button A and reset button until Arduino ide attempted to connect
then releasing it and allowing it to upload without a chance for the old code to run
