### ISSUE TITLE
where is ropg?

### ISSUE THREAD

**Issue by skysingh** [ropg/M5ez#36]
Seems like support of M5ez has been abandoned. Great shame - because it is really a nice system for M5stack ddevelopment. Hopefully ropg will find time again.

**Comment by ropg** [comment]
I've been working on some other projects, I really should return to M5ez also, and I plan to.

That said: M5ez is for developers. That means its user community must contain a few others willing and capable of working on it, expanding it and fixing things. I built it but I don't own it: we all do...

**Comment by ropg** [comment]
Just released version 2.1.0, fixing some scroll crashes.
