### ISSUE TITLE
Printing degree symbol?

### ISSUE THREAD

**Issue by andyrbarrow** [ropg/M5ez#37]
This may not specifically be for M5ez, but I'm using the library right now to create a position display for my boat. I need to be able to print a degree symbol (raised "o" character) as part of a display of latitude and longitude. The only font I can find that includes it is TomThumb, which is too small for what I need.

Anyone have any ideas?

**Comment by ropg** [comment]
> This may not specifically be for M5ez, but I'm using the library right now to create a position display for my boat. I need to be able to print a degree symbol (raised "o" character) as part of a display of latitude and longitude. The only font I can find that includes it is TomThumb, which is too small for what I need.

You could leave the space blank and draw or print separately (kinda ugly hack, but might work), or try to convert a font using my truetype2gfx tool at https://rop.nl/truetype2gfx/ .

**Comment by andyrbarrow** [comment]
Oohhh, convert a font! I'd forgotten about doing that.

I'll give it a shot. Thanks a million for a great library.

**Comment by ropg** [comment]
You could leave the space blank and draw or print separately (kinda ugly hack, but might work), or try to convert a font using my [truetype2gfx tool](https://rop.nl/truetype2gfx). The TomThumb works (I found a TrueType font file, but it doesn't seem the optimal font for information presentation.

<img width="1147" alt="Screenshot 2019-06-05 at 19 52 34 " src="https://user-images.githubusercontent.com/343196/58978128-7f939500-87cb-11e9-8e09-cf9ada1c0325.png">
