### ISSUE TITLE
How can I disable the EZ Wifi functionality?

### ISSUE THREAD

**Issue by HighTML** [ropg/M5ez#40]
I'm using EspMQTTClient which has it's own Wifi + MQTT retrying connection handling. When I run the EspMQTTClient example it show that it's reconnecting properly, however I cannot get it to work within a M5ez application. 

I tried ```#undef M5EZ_WIFI``` but that still tries to auto connect by EZ.

How can I disable the EZ Wifi functionality? I only want to use the EZ menus.

**Comment by ropg** [comment]
Remove or comment out `#define M5EZ_WIFI` from M5ez.h instead of using `undef`. (The library is compiled separately, so putting that in your sketch doesn't help.)

**Comment by HighTML** [comment]
Thanks Rob
