### ISSUE TITLE
The display of the menu overlaps with the header area.

### ISSUE THREAD

**Issue by HigashidaTomoyuki** [ropg/M5ez#42]
If I add to the menu a large number of items that do not fit on the screen, and scroll, it may overlap with the header area.

**Comment by ropg** [comment]
What? That should not happen... The m5ex-demo application has menu that scroll off screen, does it also do that with you? Could you paste code that does this?

**Comment by HigashidaTomoyuki** [comment]
Sorry for the late reply.
It was because I was modifying the code a little.
