### ISSUE TITLE
Display JPG Image

### ISSUE THREAD

**Issue by cslehel** [ropg/M5ez#5]
Hello, 

i have a minor problem and i hope you can guide me. 
I made a basic menu with 2-3 items. If i select one of them the m5stack will download an image to the SD card. 
I would like to show that image until i press a button (or a combination of 2 buttons). 
At this moment i am using the following command: 
M5.lcd.drawJpgFile(SD, filename); 
When the image stops loading the menu will show.

Thank you for considering my request.

**Comment by ropg** [comment]
Yup, that should work. I haven't worked with `HTTClient.h` nor done anything with SD cards, so I can't judge if the rest would work, but wherever you place `ez.waitForButtons("OK");` it will draw a button and wait for it to be pressed.

**Comment by cslehel** [comment]
Thank you very much, i trust you but i cant try it right now :)
