### ISSUE TITLE
'class SDLib::SDClass' has no member named 'cardType'

### ISSUE THREAD

**Issue by sysdl132** [ropg/M5ez#51]
when I compile "m5ez-demo",I got a error messege like this:
```
'class SDLib::SDClass' has no member named 'cardType'
```

**Comment by sysdl132** [comment]
first I compile a m5ez code with z-sysinfo.
```
exit status 1
'class SDLib::SDClass' has no member named 'cardType'
```
then I compile m5ez-demo(with no change)
still:
```
exit status 1
'class SDLib::SDClass' has no member named 'cardType'
```

**Comment by sysdl132** [comment]
![image](https://user-images.githubusercontent.com/54708046/73939864-51032680-4925-11ea-9706-17f9d407678a.png)

**Comment by ropg** [comment]
Oh crap. That means they changed something about the SD card interface, and now the code doesn't work anymore. Sucks.. I will try to find time soon to fix it. (But it will be march, I'm afraid..)

(Anyone up for fixing this?)

**Comment by sysdl132** [comment]
i only have a way to upload it.
disable the SD from the demo and remove SD library.

**Comment by sysdl132** [comment]
And before compiling,I disabled a line in SD/src/utility/Sd2pinmap.h:(Line 524)
```
#error Architecture or board not supported.
```
That means maybe ESP32 board is not supported.

USING:Arduino SD Library
==========================
There is an another question:Can you support M5StickC or StickV?

**Comment by sysdl132** [comment]
I also suggest you can import some labels.like:

![1](https://user-images.githubusercontent.com/54708046/74515365-6392e680-4f49-11ea-9e0e-951bb5892bdd.png)

**Comment by sysdl132** [comment]
I update the SD library and the problem fixed.Thanks.

**Comment by sysdl132** [comment]
===Do not write under this line===
