### ISSUE TITLE
print text with alignment

### ISSUE THREAD

**Issue by ralfhille** [ropg/M5ez#59]
Hi all,

i am new with the M5ez. I want to know how i can print text to a x,y position with the alignment right.

thx for help

**Comment by ropg** [comment]
M5ez's print function doesn't support that, but it is only a thin wrapper to M5.lcd's functions, which has [`setTextDatum`](https://github.com/m5stack/m5-docs/blob/master/docs/en/api/lcd.md#settextdatum), it comes with an example...
