### ISSUE TITLE
'class M5ez' has no member named 'ble'

### ISSUE THREAD

**Issue by spairo1741** [ropg/M5ez#74]
what to do to unlock BLE.
I have already uncommented on BLE in the file M5ez.h
I added a #define M5EZ_BLE line.
 I added in the submenu
subMenu.addItem ("Item A", ez.ble.menu);
I restarted Arduino, nothing helps, what I do wrong.

**Comment by paultech** [comment]
If using the Arduino library it contains pre-compiled libraries. You will need to edit this line locally https://github.com/ropg/M5ez/blob/master/src/M5ez.h#L17 and recompile.
