### ISSUE TITLE
How do I make my own header widgets?

### ISSUE THREAD

**Issue by pipy71** [ropg/M5ez#77]
Hello, I am new to this and I don't understand your instructions and was hoping you could direct me.

I would like to add a couple of widgets to the header for GSM signal and server connection, 
but I really don't understand how to even make a widget?

Do I make a widget with vector graphic or direct pixels, if so where do I put them?
Is it possible to provide some more instructions or sample code, please?

Thank you for your help.
Kind Regards.

**Comment by ropg** [comment]
The best examples for making widgets are in the M5ez code itself. For example, on line 1115 of `m5ez.cpp`, in the `ezWifi::begin()` we see `ez.header.insert(RIGHTMOST, "wifi", sizeof(cutoffs) * (ez.theme->signal_bar_width + ez.theme->signal_bar_gap) + 2 * ez.theme->header_hmargin, ez.wifi._drawWidget);`

So what that does is insert a new widget all the way on the right-hand side, called "wifi", with a width determined by the thickness of bars and gaps times the number of bars (all configurable in the theme), and then it names a function to call to draw the widget (`ez.wifi._drawwidget`). If you read [this section of the manual](https://github.com/ropg/M5ez#your-own-header-widgets) carefully and then look at the code for the various widgets in M5ez itself, you should be able to figure it out. I thought about examples, but they could not be all that much easier than what's already there.

**Comment by pipy71** [comment]
Thank you.
