### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by nak59** [ropg/M5ez#83]
Hello,
with code : 

void submenu_site(String SiteId , String NameSite) 
{
  ezMenu submenu_site(NameSite);
  submenu_site.buttons("up#Back#select##down#");
  submenu_site.txtSmall();
  submenu_site.addItem("Site Sumary");
  submenu_site.addItem("Access Points");
  //submenu_site.addItem("Switches");
  //submenu_site.addItem("Location");
  //submenu_site.addItem("Metrics");
  //submenu_site.runOnce();
  mainmenu.run();
  if (submenu_site.pickName() == "Access Points") {
    ez.msgBox("", "You pressed Access Points");
  }
  
}

pressing the back button does not move the previous menu but the main menu

**Comment by vkichline** [comment]
Could you include the function implementing the previous menu?

**Comment by nak59** [comment]
DeserializationError err = deserializeJson(doc, response);
              for (int i=0; i<sizeof(doc); i++)
                  {
                    String namesite =(doc[i]["name"].as<char*>());
                    String siteid =(doc[i]["id"].as<char*>());
                    String idnamesite = siteid +" | "+namesite;
                    if(namesite != "")
                    {
                        menusite.addItem(idnamesite);            
                    }
                  }
              }
            }
          numpage++;
           
          }
          //menusite.addItem("Back | Back to main menu");
          if (menusite.runOnce()) 
               {
                 String  id= menusite.pickName();
                 String namesite = menusite.pickCaption();
                 submenu_site(id , namesite);
               }

**Comment by vkichline** [comment]
if (menusite.runOnce()) has completed, so menusite is terminated. Try:
while(menusite.runOnce()) {
    String  id= menusite.pickName();
   ...
}

**Comment by nak59** [comment]
It's work :) Thks so much

**Comment by paultech** [comment]
Glad to hear this is working :)

@vkichline as you mentioned in chat, This would be a good case to write an example for.
